### ISSUE TITLE
Error : Missing credentials in config , when trying to register a new user

### ISSUE THREAD

**Issue by apurva-parad** [awslabs/aws-cognito-angular2-quickstart#10]
Hi,
I am facing an issue with the app when trying to register a new user.
I get the following error : 
Missing credentials in config

With my existing user I am able to sign in.

Could you please guide me, what could be the problem ??

Thanks,
Apurva

**Comment by vbudilov** [comment]
Hi @apurva-parad , 

Thanks for reaching out. What are the steps to replicate this error? 

Thanks,
Vladimir

**Comment by apurva-parad** [comment]
Hi Vladimir,
Thanks for you response.

Following are the steps i have implemented: 
1. Got the project cloned 
2. Had a already existing user pool and Identity pool (added policies as per required from createresource.sh file)
3. Created a dynamodb table and s3 bucket using the script.
4. Installed required tools: npm, aws-cli, bower, angular-cli
5. Made changes in aws.service.ts - changed the dynamodb table name
6. Made changes in cognito.service.ts - Region, Userpool, Identity pool
7. Followed the steps mentioned in readme document. 

Thanks,
Apurva

**Comment by vbudilov** [comment]
If you use the credentials that the app comes with, does it still fail?

**Comment by apurva-parad** [comment]
I dont get any issues, when i use your Identity pool and userpool details. No errors.
Its working fine.

I have given the policies required for authenticated and unauthenticated roles to identity pool.
Is there something that I am missing ?

**Comment by chris-munn** [comment]
@apurva-parad, how did you fix this in the end, did you have to enable unauthenticated users in your identity pool?

**Comment by apurva-parad** [comment]
@Munnster83 , I got this fixed by giving proper roles to my Identity pool.

**Comment by quantuminformation** [comment]
@apurva-parad could you create a video or guide step by step on what you have done for the community?
