### ISSUE TITLE
How to get  and display single data from a string in a array 

### ISSUE THREAD

**Issue by chris86** [awslabs/aws-cognito-angular2-quickstart#100]
Hi I just went through your code and I am trying something  in the useractivitycomponent.ts there is this code  `public logdata: Array<Stuff> = [];`
now I am trying to get the type or date at postition 0 in the component file I i tried  doing different things but cant get it to work I am learning Typescript
`public myHero = this.logdata[0];`
`public stuff: Stuff = new Stuff();`
`public mmm: string = this.stuff.date;`
`public myfirstdate: string = this.stuff[0].date;`

I hope you understand what i am trying to do I am trying to get the first object in the array  "date"

**Comment by vbudilov** [comment]
Hi @chris86 , 

This is more of a JS question rather than a Cognito question, so you might want to use stackoverflow for that. 

Vladimir
