### ISSUE TITLE
Deployment of aws-cognito-angular2-quickstart project to Aws Elasticbeanstalk Failed

### ISSUE THREAD

**Issue by meayyappa** [awslabs/aws-cognito-angular2-quickstart#103]
"ng build --prod" failed while deploying to Aws Elastic Beanstalk,

Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/55_build_angular.sh failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
INFO: Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].
WARN: Environment health has transitioned from Pending to Degraded. Command failed on all instances. Initialization completed 10 seconds ago and took 4 minutes.
ERROR: Create environment operation is complete, but with errors. For more information, see troubleshooting documentation.

**Comment by vbudilov** [comment]
Can you try it again?
