### ISSUE TITLE
createResources.sh does not work on Windows

### ISSUE THREAD

**Issue by deanpeterson** [awslabs/aws-cognito-angular2-quickstart#105]
There are a number of file locations hard coded into the sh file. The paths are incompatible with windows. A few things complete successfully but most of the commands fail on Windows.

I tried installing babun. I get the same errors:

> An error occurred (NoSuchEntity) when calling the GetRole operation: Role not found for angularcognitotest3-authenticated-role
> 
> Error parsing parameter '--policy-document': Unable to load paramfile file:///tmp/authrole-trust-policy.json: [Errno 2] No such file or directory: u'/tmp/authrole-trust-policy.json'
> 
> Error parsing parameter '--policy-document': Unable to load paramfile file:///tmp/authrole.json: [Errno 2] No such file or directory: u'/tmp/authrole.json'
> Created user pool with an id of  us-east-2_W8BPkDZ3H
> Created user pool client with id of  56gp0ug11mhb2gqj0732hjhvbo
> 
> Parameter validation failed:
> Invalid length for parameter Roles.unauthenticated, value: 0, valid range: 20-inf
> Invalid length for parameter Roles.authenticated, value: 0, valid range: 20-inf
> make_bucket: cognitosample-angularcognitotest3
> S3 bucket successfully created. Uploading files to S3.
> 
> Error parsing parameter '--policy': Unable to load paramfile file:///tmp/s3-bucket-policy.json: [Errno 2] No such file or directory: u'/tmp/s3-bucket-policy.json'
> Building the project
> You are running version 6.2.2 of Node, which will not be supported in future
> versions of the CLI. The official Node version that will be supported is 6.9 and greater.
> 
> To disable this warning use "ng set --global warnings.nodeDeprecation=false".The package "angular-cli" has been renamed to "@angular/cli". The old package will be deprecated soon.
> 
> Please take the following steps to avoid issues:
> "npm install --save-dev @angular/cli@latest"

**Comment by chris86** [comment]
that is true check this post
https://github.com/awslabs/aws-cognito-angular2-quickstart/issues/95

**Comment by vbudilov** [comment]
Yes, the shell script won't work on Windows -- only Linux and Mac supported.
