### ISSUE TITLE
Facebook Identity Federation

### ISSUE THREAD

**Issue by luketn** [awslabs/aws-cognito-angular2-quickstart#107]
Would you consider adding Facebook sign-in?

I think that it would round out the example and is a great alternative to creating a new username/password for registration

Love the app - great reference implementation of Cognito and Angular!

**Comment by vbudilov** [comment]
Thanks Luke. At this time I don't have any plans on adding FB integration, but I do accept PRs :)

**Comment by mqasem92** [comment]
Hi, it will be great if you add Facebook and Google login.

Please consider it
