### ISSUE TITLE
quickstart is for deprecated Angular2 router 

### ISSUE THREAD

**Issue by davemo88** [awslabs/aws-cognito-angular2-quickstart#11]
This quickstart code is for the older deprecated version of the Angular2 router. Needs to be updated as in:

https://medium.com/@blacksonic86/upgrading-to-the-new-angular-2-router-255605d9da26#.xq2q4h5da

or similarly

**Comment by vbudilov** [comment]
Hi @davemo88 , 

Working on upgrading the project to the angular 2 Final version. 

Thanks,
Vladimir

**Comment by davemo88** [comment]
Awesome. I know Angular2 is a bit of a moving target at the moment. Thanks!

edit: also I appreciate your work on this quickstart as it was very helpful for me as a first time Cognito user.

**Comment by vbudilov** [comment]
Updated to angular 2.1.1
