### ISSUE TITLE
Hiding page source from browser

### ISSUE THREAD

**Issue by makulis** [awslabs/aws-cognito-angular2-quickstart#134]
How was hiding the page source from the browser achieved? 

The aws cognito details (app id and user pool id) can be easily found from the browser by viewing the page source and navigating the javascripts. This is a security issue.

Thanks in advance.

**Comment by sentisci** [comment]
Has this issue been resolved and then closed ?

**Comment by makulis** [comment]
No it has not been resolved. I opened a new issue and asked the question differently hoping that maybe someone will offer some guidance.
