### ISSUE TITLE
Couldn't get session

### ISSUE THREAD

**Issue by vinodhum** [awslabs/aws-cognito-angular2-quickstart#14]
Hi,
I am getting below error 
`Couldn't get the session: CredentialsError: Missing credentials in config CredentialsError: Missing credentials in config`
after login I can call AWS resource fine but after some time I guess 1hr or so, I get above error.
looks like session is getting expired how do I handle it ? or what does above error means ?
once I re-login error goes away,  but token expired is set to 30 days in AWS and then why is it getting expired in short time.

**Comment by vbudilov** [comment]
Hi @vinodhum,

Can you please document the steps needed to replicate this error? 

Thanks,
Vladimir

**Comment by vinodhum** [comment]
nothing special
created user pool
created federated Identity 
login using  UserLoginService.authenticate
and it authenticates fine.

but after 1 hr sessions gets expired and below error.
Couldn't get the session: CredentialsError: Missing credentials in config CredentialsError: Missing credentials in config

to handle this error i have to re-login and after re-login I have to refresh site for some reason for  other pages to pick up new auth token.

firstly how to increase the session time form 1hr to let say 10hrs
how to handle refresh token  post process so that I have to manly refresh the website for all the pages to pickup new auth.

**Comment by petergerten** [comment]
Not sure why this got closed without answer. I ran into the same timeout issue and don't know here to change it. Any ideas?
