### ISSUE TITLE
Authentication Role and Create Account issues

### ISSUE THREAD

**Issue by KoldBrewEd** [awslabs/aws-cognito-angular2-quickstart#17]
Just wanted to point out the policy on aws/authrole.json is pointing to a specific account and this is causing errors to query the DDB table. I had to manually edit the policy in IAM to point to the correct table.

I am also getting the following error to create an account:

```
POST https://cognito-idp.ap-northeast-1.amazonaws.com/ 400 (Bad Request) 
XHR finished loading: POST "https://cognito-idp.ap-northeast-1.amazonaws.com/".scheduleTask @ zone.js:1274
result: Username cannot be of email format, since user pool is configured for email alias. @ auth.component.ts:261 
```

I'm trying with:

user: jdoe
email: jdoe@email.com

Other than that, it works like a charm. Great stuff!

**Comment by vbudilov** [comment]
Hi @awsed , 

I'll include a note in the README file. 

Thanks,
Vladimir
