### ISSUE TITLE
why is the UserLoginService used static

### ISSUE THREAD

**Issue by mxab** [awslabs/aws-cognito-angular2-quickstart#19]
Hi,
I'm just browsing through the code but do not fully understand why the UserLoginService is used with static methods and importing it instead of injecting a instance via the constructor?

**Comment by vbudilov** [comment]
Hi @mxab , 

When I was writing this app, angular 2 was still in beta and a lot of things, including the IoC methodology, syntax & initialization, was in flux (breaking changes with almost every new version). I wanted to make sure that it would be easy to transition the code to a final state once Angular Final comes out. 

In general, I'd definitely use injection now, rather the static classes. 

Thanks,
Vladimir

**Comment by mxab** [comment]
Hi @vbudilov,
I understand, thanks for clarifying. I was not sure if I missed something.
