### ISSUE TITLE
Angular 1?

### ISSUE THREAD

**Issue by ribomation** [awslabs/aws-cognito-angular2-quickstart#2]
Are you planning to release an Angular 1 version as well?

That would be helpful. Because, the Cognito SDK is in JavaScript not TypeScript.
Angular 2 is still in beta and constantly changing even for the latest release candidates.
That mean, few persons would _right now_ jump on the Angular 2 band wagon for a production strength mission critical app.

**Comment by vbudilov** [comment]
Hi @ribomation, 

At this time I'm not planning on releasing the Angular 1 version of this app. Angular2 development seems to be coming along very well, and a release looks to be close (just speculating here). 

Thanks,
Vladimir
