### ISSUE TITLE
Which version of angular-cli?

### ISSUE THREAD

**Issue by taji** [awslabs/aws-cognito-angular2-quickstart#20]
Just forked your repository today.  Just to verify, when installing angular-cli globally, the beta-19 version is installed. However, the package.json installs beta-14 locally.  Which version should we be using and is the global install necessary?

**Comment by taji** [comment]
Also, is bower used?  I'm not seeing it in the package.json and there is no bowerrc file in the project, but your readme indicates it's required.

**Comment by vbudilov** [comment]
Hi @taji , 
1. I'm using version 14, but try the latest first -- if that doesn't work then revert to 14. You can also run ng --version to see which version is being used
2. I removed the bower dependency, but forgot to update the README...I have it on my todo now. 

Thanks,
Vladimir

**Comment by taji** [comment]
Thanks am trying latest version will let you know how it goes. 

Also, I believe "typings install" is no longer necessary as well.

**Comment by vbudilov** [comment]
Updated README
