### ISSUE TITLE
createResources.sh: ROOTNAME format causing problems. 

### ISSUE THREAD

**Issue by taji** [awslabs/aws-cognito-angular2-quickstart#21]
The ROOT_NAME (and thus the BUCKET_NAME) variable have a problem in that if you use camel case (as the author does), then the command (on line 14 of aws\createResources.sh):

````
aws s3 website s3://$BUCKET_NAME/ --index-document index.html --error-document index.html
````
Results in this error:

*An error occurred (InvalidBucketName) when calling the PutBucketWebsite operation: The specified bucket is not valid.*

The fix is to use lowercase (snake-case is ok) for the ROOT_NAME variable (and thus the BUCKET_NAME).

However, if you do use snake-case for the ROOT_NAME, then the this will mess up the IDENTITY_POOL_NAME used in this command (on line 30):

````
aws cognito-identity create-identity-pool --identity-pool-name $IDENTITY_POOL_NAME --allow-unauthenticated-identities --region $REGION| grep IdentityPoolId | awk '{print $2}' | xargs |sed -e 's/^"//'  -e 's/"$//' -e 's/,$//' > /tmp/poolId
````

Which results in this error:

*An error occurred (ValidationException) when calling the CreateIdentityPool operation: 1 validation error detected: Value 'dev-day2' at 'identityPoolName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w ]+*

The fix is to assign a whole new value to $IDENTITY_POOL_NAME that uses either CamelCase or underscore_case to separate the words.

In order to get the script to run properly,  I have the variables set as so:

````
ROOT_NAME=dev-day2
BUCKET_NAME=user-$ROOT_NAME
TABLE_NAME=login-trail-$ROOT_NAME
ROLE_NAME_PREFIX=$ROOT_NAME
POOL_NAME=$ROOT_NAME
IDENTITY_POOL_NAME=dev_day2
REGION=us-east-1
````

I'm running aws-cli version : aws-cli/1.11.11 Python/2.7.6 Linux/4.2.0-c9 botocore/1.4.68

Can anyone confirm?

**Comment by vbudilov** [comment]
Hi @taji , 

$BUCKET_NAME is just a variable - it resolves to whatever you set it to, and this happens before the 'aws' command executes. 

Are you sure you've set the variables correctly? 

I would suggest you go through the steps of setting up Cognito manually initially. I will update this script with the rest of the steps later on, since some of the features weren't available when I created this project. 

Thanks,
Vladimir

**Comment by vbudilov** [comment]
Closing since the problem, most likely, isn't related to aws-cli
