### ISSUE TITLE
npm start does not work for me

### ISSUE THREAD

**Issue by mhafren** [awslabs/aws-cognito-angular2-quickstart#22]
I just tried out getting a local copy of your quickstart. I ran into some problems. The install went fine but when I ran npm start I got errors. I have attached the npm.debug.log. Do you have any ideas why it does not start? 

Attached you can find the output of the log.
![screenshot 2016-11-10 22 03 34](https://cloud.githubusercontent.com/assets/551907/20194167/9e960ca2-a791-11e6-9b55-a3eb075d0dab.jpg)

**Comment by vbudilov** [comment]
Hi @mhafren , 

what's your ng and node version? 

Here's mine: 
angular-cli: 1.0.0-beta.14
node: 6.9.1

**Comment by mhafren** [comment]
Hi @vbudilov ,

I am using node 6.5 (will upgrade). However I got it working now, seems I had another program occupying the port 4200 that caused this issue. Sorry for the invalid issue report and thank you a lot for the response!

**Comment by vbudilov** [comment]
Glad it worked :)
