### ISSUE TITLE
Why not add npm bootstrap dependancy?

### ISSUE THREAD

**Issue by quantuminformation** [awslabs/aws-cognito-angular2-quickstart#23]
Would make it easier to upgrade or change version. Also would be nice to see the AWS SDK's as part of npm.

**Comment by vbudilov** [comment]
Hi @QuantumInformation , 

The npm bootstrap dependency had issues recently, so it made sense to take that out, especially since it's part of the UI and npm isn't really needed there. In regards to the AWS SDK's npm dependency -- it's on the roadmap. 

Thanks,
Vladimir

**Comment by quantuminformation** [comment]
thx, good to know! Nice work on the TS!

**Comment by quantuminformation** [comment]
Would love Typings too with the AWS stuff if possible.
