### ISSUE TITLE
[feature request] It would be great if AWS could sponsor a youtube video on all the steps to get this to run including setting up amazon resources. EOM

### ISSUE THREAD

**Issue by quantuminformation** [awslabs/aws-cognito-angular2-quickstart#26]

**Comment by vbudilov** [comment]
Hi @QuantumInformation, 

Thanks for your feedback. Do you have any specific questions? There's nothing on the roadmap at this time to  create a youtube video of the step. Also, for the most part, the steps are automated, except for the creation of the cognito user pool, which is on the roadmap. 

Thanks,
Vladimir

**Comment by quantuminformation** [comment]
Well I haven't done much with the AWS interface, would be nice if a video could be made with all the steps to setup everything (AWS config, local steps once project is checked out) from Green, for someone who has never used these tools. Will save reading time. I've spent the last few years on frontend so this is all a bit strange territory for me.

**Comment by vbudilov** [comment]
Understood. There are a lot of youtube videos out there. Here's one of them: https://www.youtube.com/watch?v=KTcDy704GiY

Search for re:Invent talks.

**Comment by quantuminformation** [comment]
In the sh file, what is ROOT_NAME=DevDay2 ?

**Comment by vbudilov** [comment]
It's a placeholder variable. Take a look at how it's used -- that should provide more context.
