### ISSUE TITLE
Rc.4

### ISSUE THREAD

**Issue by hashitha** [awslabs/aws-cognito-angular2-quickstart#3]
I just tried with Angular 2 rc4 and it doesn't seem to work.

**Comment by vbudilov** [comment]
What errors are you seeing? Can you post more info?

**Comment by vbudilov** [comment]
@hashitha I've moved the project to angular RC.4. I also upgraded the angular routing to v3.beta2 - which extracts the routing configuration from the actual components. Check out the new code. 
Thanks!
