### ISSUE TITLE
Redundant AWS-SDK and AWS-Cognito-SDK?

### ISSUE THREAD

**Issue by MichaelCPell** [awslabs/aws-cognito-angular2-quickstart#30]
My understanding is that the AWS-Cognito-SDK is just the Cognito module of the AWS-SDK.  If we are importing AWS-SDK, is it necessary to include both?

**Comment by vbudilov** [comment]
Hi @MichaelCPell , 

Per the official documentation you need to include both: 
https://github.com/aws/amazon-cognito-identity-js

Vladimir

**Comment by MichaelCPell** [comment]
Thanks Vlad!

I will make a pull request if I can demo that they are redundant.
