### ISSUE TITLE
an example that invokes a lambda

### ISSUE THREAD

**Issue by ababkin** [awslabs/aws-cognito-angular2-quickstart#32]
Hi

I'm trying to change the example to call lambda instead of writing to ddb (pretty much at the same spot in code), and unfortunately i get this error:

```
Unable to call lambda. Error JSON: {
  "message": "Missing credentials in config",
  "code": "CredentialsError",
  "time": "2017-01-04T02:19:56.970Z",
  "originalError": {
    "message": "No credentials to load",
    "code": "CredentialsError",
    "time": "2017-01-04T02:19:56.970Z"
  }
}
```

It would be great if someone could add a working example of calling a lambda

Thanks!

EDIT: oh an btw, the original example functionality works just fine and it creates DDB records on each login

**Comment by vbudilov** [comment]
It's actually no different than calling DDB directly. Most likely you're initializing the Lambda Client before you've been authenticated or your tokens are expired. 

The following needs to be done after the AWS credentials have been updated using the cognito flow:

> var lambda = new AWS.Lambda();
lambda.addPermission(params, function (err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});

**Comment by ababkin** [comment]
@vbudilov thanks so much for the prompt answer

this did it!

**Comment by vbudilov** [comment]
Glad it helped :)
