### ISSUE TITLE
sjcl, paranoia and entropy

### ISSUE THREAD

**Issue by adamclerk** [awslabs/aws-cognito-angular2-quickstart#43]
https://github.com/aws/amazon-cognito-identity-js/#random-numbers

The amazon-cognito-identity-js mentions using a paranoia of greater than 0 and calling startCollectors() on the sjcl library to provide entropy for older browser and mobile os'.

Any reason why it was not done within this quick start?

**Comment by ghost** [comment]
I believe this may be the reason.

https://github.com/aws/amazon-cognito-identity-js/pull/262/commits/e4fa8162c2921830be2ebc6d49fef121dcec3954

**Comment by adamclerk** [comment]
That PR was rejected and not pulled in.

It looks like this PR resolved the issue.

https://github.com/aws/amazon-cognito-identity-js/pull/281

Which makes my question moot.

Next question. Do you have plans to update the quickstart to use the new aws js lib (1.13.0)?

**Comment by vbudilov** [comment]
@adamclerk , 

There's no plan to upgrade the aws js lib as of now. You can use the following link to customize your sdk with the latest code: https://sdk.amazonaws.com/builder/js/
