### ISSUE TITLE
Freature: Login With Facebook, Google

### ISSUE THREAD

**Issue by rakeshtembhurne** [awslabs/aws-cognito-angular2-quickstart#45]
It would be great if we can add login with Facebook, Google and other social media accounts with AWS Cognito.

**Comment by vbudilov** [comment]
Hi @rakeshtembhurne , 

This is not on the roadmap yet, but most of the code is related to actual FB (or other social providers') login, not to Cognito. Here's a nice blog post about that: https://aws.amazon.com/blogs/developer/authentication-in-the-browser-with-amazon-cognito-and-public-identity-providers/

Vladimir

**Comment by sanjaychavan1991** [comment]
If possible please make it available, that will be a great help. Either at least suggest some blogs so I can use that in this code only.

Thanks in advance.
