### ISSUE TITLE
Requesting instructions

### ISSUE THREAD

**Issue by Vingtoft** [awslabs/aws-cognito-angular2-quickstart#46]
Where can I find instructions or a tutorial to get this to work?

**Comment by vbudilov** [comment]
The README has the detailed instructions. 

Vladimir

**Comment by Vingtoft** [comment]
Thanks for the quick answer, Vladimir.
I dont think the README provides enough information. 
Example: No instructions on changing the `aws/createResources.sh` file which is necessary: 

```
#!/usr/bin/env bash

ROOT_NAME=budilovdelete
# Bucket name must be all lowercase, and start/end with lowecase letter or number
# $(echo...) code to work with versions of bash older than 4.0
BUCKET_NAME=budilov-$(echo "$ROOT_NAME" | tr '[:upper:]' '[:lower:]')
TABLE_NAME=LoginTrail$ROOT_NAME

# Replace with your 12-digit AWS account ID (e.g., 123456789012)
AWS_ACCOUNT=540403165297
ROLE_NAME_PREFIX=$ROOT_NAME
POOL_NAME=$ROOT_NAME
IDENTITY_POOL_NAME=$ROOT_NAME
REGION=us-west-2
```

Is there any other necessary steps that is not described in the README? 
I cannot get it to work.

Thanks

**Comment by coldcam** [comment]
GREETINGS @Vingtoft ,

I managed to get this to work.  I might be able to help if it is still not working for you.

Let me know what errors you are getting.

Regards

**Comment by Vingtoft** [comment]
Thank you for your kind offer. 
I got it to work after the readme was updated a few days ago.
