### ISSUE TITLE
How to make Lambda call through API services using credentials received from Cognito?

### ISSUE THREAD

**Issue by robertbrower-technologies** [awslabs/aws-cognito-angular2-quickstart#48]
Thanks for the quickstart. It works very nicely. Now that my users can sign up and log in, I want them to be able to perform functions in my web app that call Lambda functions through the API gateway. I know that goes beyond the scope of this quickstart, but having secure access to "something" is I guess the point of Cognito. I know how to write Lambda functions. I am using one to do some work when during the pre-signup. But I want to be able to call an API gateway that is secured by this app which calls a Lambda and returns it's result to the web app. Thank you.

**Comment by vbudilov** [comment]
Makes perfect sense. I created another project that specifically demos this functionality: https://github.com/awslabs/serverless-photo-recognition

Once setup, you will be able to call API Gateway, which, in turn, will call a Lambda function. 

Vladimir
