### ISSUE TITLE
[question] why not used AWS.config.credentials.clearCachedId() before login 

### ISSUE THREAD

**Issue by mickadoua** [awslabs/aws-cognito-angular2-quickstart#49]
if I understand correctly, you use   `AWSCognito.config.update({accessKeyId: 'anything', secretAccessKey: 'anything'});`  (here https://github.com/awslabs/aws-cognito-angular2-quickstart/blob/master/src/app/service/cognito.service.ts#L220 ) 
to reset credential before re login ? 

why not used AWS.config.credentials.clearCachedId()  ?

thank you

**Comment by aassaad** [comment]
By the time `update` is called there, `UserLoginService.isAuthenticated` has already fired, checking localStorage for cached id/credentials (in `this.getCurrentUser` and `currentUser.getSession`). If there's a cached ID + valid tokens you'll bypass `UserLoginService.authenticate`. If there are expired tokens it'll either refresh and bypass it, or fail `isAuthenticated` and end up on the login page, where calling `authenticate` gets whatever ID is tied to the username/password and overwrites the cached one.

So the only time `clearCachedId` is necessary is when you're signing out and need to clear the *valid* tokens + refresh token from localStorage— that's handled internally by `cognitoUserPool.signOut`.

But why is AWSCognito.config.update called at all, then?

Before the GA release of User Pools (~07/16), if you were using both the slimmed-down SDK *and* the main SDK, it was necessary to either directly set credentials on both `AWS.config` and `AWSCognito.config` (with `new AWS.CognitoIdentityCredentials({
IdentityPoolId: '...'}`)  *or* call `AWSCognito.config.update` with placeholder `accessKey` and `secretAccessKey` values before making any client requests that require authentication by default (e.g. on a User Pool with unauth access disabled).

As far as I understand this was a result of `CognitoUserPool` and `CognitoUser` calling methods on their internal `AWSCognito.CognitoIdentityProvider` client which asserted credentials were *defined* but not necessarily valid, *before* it was possible to get credentials for a user, requiring placeholder credentials from somewhere. See https://github.com/aws/amazon-cognito-identity-js/pull/25.

Around the time of GA release, those methods were changed to use `makeUnauthenticatedRequest` internally so it looks like that call to `AWSCognito.config.update` may not actually be necessary.
https://github.com/aws/amazon-cognito-identity-js/commit/f7a4b88d3cd40a3417999dae2f5c50e0feff51ce
https://github.com/aws/amazon-cognito-identity-js/commit/0b6fc8f68446bc8fab2f7f13038d6b6533ca6f4a
