### ISSUE TITLE
Ionic 2 integration

### ISSUE THREAD

**Issue by sirfak** [awslabs/aws-cognito-angular2-quickstart#5]
Hi
Hiw can i integrate this with my existing ionic 2 project?
Thanks
sirfak

**Comment by vbudilov** [comment]
Hi Sirfak, 

This project was meant to be used to demo the Amazon Cognito functionality in the browser. I haven't worked on making it work in ionic, but you'll have to change the 'views' and some of the 'routing' logic. Most of the code can stay the same -- that's the biggest advantage here. 

Thanks,
Vladimir
