### ISSUE TITLE
Specify aws credentials account

### ISSUE THREAD

**Issue by 22Viig** [awslabs/aws-cognito-angular2-quickstart#52]
I have many accounts in my ~/.aws/credentials file , is possibile to launch createResource.sh specifying which aws account to use?

**Comment by vbudilov** [comment]
Hi @RickyGeek , 

At this time this is not on the roadmap. I'd suggest you set a default profile when you run the script. 

Vladimir

**Comment by claydozed** [comment]
Would it be possible to specify which profile to use by changing this line in createResource.sh  
`aws_cmd=${aws_cmd:-aws}`
to 
`aws_cmd=${aws_cmd:-aws --profile [example-profile]}` ?
