### ISSUE TITLE
issue on npm start

### ISSUE THREAD

**Issue by natanielkdias** [awslabs/aws-cognito-angular2-quickstart#53]
I'm having a issue when i try the npm start command.
And, when I run ng serve command occurs the below error:

Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "undefined".

**Comment by vbudilov** [comment]
What steps did you follow to get to that error? Did you take a look at the requirements? e.g. did you install NG CLI?

**Comment by natanielkdias** [comment]
Hi,
I did:
git clone
npm install
npm start

to see the detailed error I did ng serve.

Btw my OS is Windows 10

Thanks in advance

**Comment by vbudilov** [comment]
Take a look at the "required tools" section. You probably don't have ng cli installed.

**Comment by natanielkdias** [comment]
I have, I updated it now, but the issue remains.

**Comment by vbudilov** [comment]
Post what you see when you run: ng --version

**Comment by natanielkdias** [comment]
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0-rc.4
node: 6.9.1
os: win32 x64
@angular/common: 2.2.4
@angular/compiler: 2.2.4
@angular/compiler-cli: 2.2.4
@angular/core: 2.2.4
@angular/forms: 2.2.4
@angular/http: 2.2.4
@angular/platform-browser: 2.2.4
@angular/platform-browser-dynamic: 2.2.4
@angular/platform-server: 2.2.4
@angular/router: 3.2.4
@angular/cli: 1.0.0-rc.4
```

**Comment by vbudilov** [comment]
Try upgrading your node version to the latest one (I have 7.7.3)

**Comment by natanielkdias** [comment]
Hi,
I upgraded node (to 7.7.4) and the issue remains,
Then I upgraded all dependencies with npm-check and now the project runs. 
However, there's a new issue: seems that project doesn't recognize the files on assets folder. I think it's happening cause  I upgraded the angular-cli to your last version in which the package name changed from angular-cli to @angular/cli.
I needed to do some changes on package.json too:

```
//From:
...
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
...
//To:
...
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
...
```

**Comment by vbudilov** [comment]
When you upgrade the same issue remained? If you're using the latest ng cli you needed to upgrade the cli json. Also, did you get this to work?

**Comment by natanielkdias** [comment]
It worked when I changed the reference of asset files from "assets/..." to "src/assets".

**Comment by jameshow** [comment]
@vbudilov 
> you need to update the cli json

I am having the same problem; do you mean to update angular-cli.json file?

```
$ ng --version
@angular/cli: 1.0.0-rc.4
node: 7.7.4
os: darwin x64
@angular/common: 2.2.4
@angular/compiler: 2.2.4
@angular/compiler-cli: 2.2.4
@angular/core: 2.2.4
@angular/forms: 2.2.4
@angular/http: 2.2.4
@angular/platform-browser: 2.2.4
@angular/platform-browser-dynamic: 2.2.4
@angular/platform-server: 2.2.4
@angular/router: 3.2.4
@angular/cli: 1.0.0-rc.4
```

**Comment by vbudilov** [comment]
I've updated the codebase to angular cli 1.0.0-rc.2 and pushed the code to the repo.

**Comment by jameshow** [comment]
I was working on the same.  On the latest, I'm still getting a few dependency errors but I will submit a PR with a dependency tree that worked for me.

**Comment by vbudilov** [comment]
Also, upgraded to Angular v4.
