### ISSUE TITLE
Bower install is broken.

### ISSUE THREAD

**Issue by taji** [awslabs/aws-cognito-angular2-quickstart#6]
```
bower startbootstrap-sb-admin-2#1.0.8                ENORESTARGET No tag found that was able to satisfy 1.0.8

Additional error details:
No versions found in https://github.com/IronSummitMedia/startbootstrap-sb-admin-2.git
```

Due to broken bootstrap theme dependency as described here:

[https://github.com/ironsummitmedia/startbootstrap-sb-admin-2/issues/1](url)

FYI, I used golovchanskiy's temporary workaround to point to the proper repo. Just update the bower.json as so:

```
"startbootstrap-sb-admin-2": "https://github.com/BlackrockDigital/startbootstrap-sb-admin-2.git#master",
```

Bower install is working, still need to test the demo.

**Comment by degt** [comment]
@taji 

startbootstrap-sb-admin-2 is broken. https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/issues/130#issuecomment-241149914

To fixed change bower.json dependencies:

"startbootstrap-sb-admin-2": "https://github.com/BlackrockDigital/startbootstrap-sb-admin-2.git"
