### ISSUE TITLE
How to retrieve event.response?

### ISSUE THREAD

**Issue by robertbrower-technologies** [awslabs/aws-cognito-angular2-quickstart#60]
I have a onPostAuthentication lambda function set up and being called on my user pool's post authentication trigger. In this function I set event.response.accessToken = accessToken;

How can I retrieve this token in my Angular 2 single page app when a user logs in?

Thank you!

Robert

**Comment by vbudilov** [comment]
Take a look at the CognitoUtil.getAccessToken function.

**Comment by robertbrower-technologies** [comment]
My question was more related to how to pass things back in event.response of a lambda to the caller via the callback method and retrieve them in the webapp via the api.
