### ISSUE TITLE
What is best solution to process facebook data? 

### ISSUE THREAD

**Issue by PiotrKalinski** [awslabs/aws-cognito-angular2-quickstart#63]
I'd like to invoke function from frontend to fetch facebook comments, process them and send to s3. What Is best solution? Do you have any docs about using facebook api with lambda/kinesis?

**Comment by vbudilov** [comment]
You can use the FB's JS libraries in this angular app as you would with any other app. 

In regards to saving to S3 -- use our aws js s3 sdk: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html

In regards to Lambda/Kinesis -- that all depends on your use case. Take a look at the FB's docs: https://developers.facebook.com/docs/apis-and-sdks

Writing to Kinesis is directly correlated with your use case, so I can't really suggest anything unless I know what it is (and this forum might not be the best one for a Kinesis conversation). :)
