### ISSUE TITLE
default checkout and quickstart project (without mods) fails to build with --prod, otherwise seems ok

### ISSUE THREAD

**Issue by greendavegreen** [awslabs/aws-cognito-angular2-quickstart#65]
checked out the latest master branch and ran through the quickstart:
commit revision as it stands now:
de8a036ae676db40987004d50a0767814cc947f4   (apr 11th)

just followed the quickstart, ran createResources.sh.  the app runs locally in developer mode.  the app also runs fine from the s3 website.

All appears to be healthy until you suggest the following as a way to deploy going forward:
`npm run build; cd dist; aws s3 sync . s3://cognitosample-vmgen`

npm run build fails on in my environment:

I attempt npm run build  (which does ng build --prod)  and this occurs:
ng build --prod

Hash: 7d29103d959cd1d7c4ef                                                               
Time: 13763ms
chunk    {0} main.6b9b83cba9765e3a9a6b.bundle.js (main) 310 kB {2} [initial] [rendered]
chunk    {1} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {3} [initial] [rendered]
chunk    {2} vendor.f06d8c69bceb45128a38.bundle.js (vendor) 1.6 MB [initial] [rendered]
chunk    {3} inline.94cce977880e64d20277.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in ng:///Users/dgreen/code/aws-cognito-angular2-quickstart/src/app/public/auth/register/registration.html (26,17): Supplied parameters do not match any signature of call target.

ERROR in ng:///Users/dgreen/code/aws-cognito-angular2-quickstart/src/app/secure/landing/secureHome.html (25,25): Property 'userName' does not exist on type 'SecureHomeComponent'.

ERROR in ng:///Users/dgreen/code/aws-cognito-angular2-quickstart/src/app/public/auth/login/login.html (21,17): Supplied parameters do not match any signature of call target.

ERROR in ng:///Users/dgreen/code/aws-cognito-angular2-quickstart/src/app/public/auth/forgot/forgotPassword.html (15,17): Supplied parameters do not match any signature of call target.
ng:///Users/dgreen/code/aws-cognito-angular2-quickstart/src/app/public/auth/forgot/forgotPasswordStep2.html (20,17): Supplied parameters do not match any signature of call target.

ERROR in ng:///Users/dgreen/code/aws-cognito-angular2-quickstart/src/app/public/auth/confirm/confirmRegistration.html (20,17): Supplied parameters do not match any signature of call target.

ERROR in ng:///Users/dgreen/code/aws-cognito-angular2-quickstart/src/app/public/auth/resend/resendCode.html (15,17): Supplied parameters do not match any signature of call target.

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/dgreen/.nvm/versions/node/v7.8.0/bin/node" "/Users/dgreen/.nvm/versions/node/v7.8.0/bin/npm" "run" "build"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

The logfile that was produced as "debug output from npm run build is:

1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle aws-cognito-angular2-quickstart@1.0.0~prebuild: aws-cognito-angular2-quickstart@1.0.0
6 silly lifecycle aws-cognito-angular2-quickstart@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle aws-cognito-angular2-quickstart@1.0.0~build: aws-cognito-angular2-quickstart@1.0.0
8 verbose lifecycle aws-cognito-angular2-quickstart@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle aws-cognito-angular2-quickstart@1.0.0~build: PATH: /Users/dgreen/.nvm/versions/node/v7.8.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/dgreen/code/aws-cognito-angular2-quickstart/node_modules/.bin:/Users/dgreen/.nvm/versions/node/v7.8.0/bin:/Users/dgreen/.virtualenvs/bot3_scripting/bin:/Users/dgreen/.jenv/shims:/usr/local/sbin:/Users/dgreen/.jenv/bin:/Users/dgreen/bin:/Users/dgreen/bin:/usr/games/bin:/Users/dgreen/.rvm/gems/ruby-2.1.2/bin:/Users/dgreen/.rvm/gems/ruby-2.1.2@global/bin:/Users/dgreen/.rvm/rubies/ruby-2.1.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/dgreen/.rvm/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/dgreen/.rvm/bin:/opt/metasploit-framework/bin:/opt/metasploit-framework/bin
10 verbose lifecycle aws-cognito-angular2-quickstart@1.0.0~build: CWD: /Users/dgreen/code/aws-cognito-angular2-quickstart
11 silly lifecycle aws-cognito-angular2-quickstart@1.0.0~build: Args: [ '-c', 'ng build --prod' ]
12 silly lifecycle aws-cognito-angular2-quickstart@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle aws-cognito-angular2-quickstart@1.0.0~build: Failed to exec build script
14 verbose stack Error: aws-cognito-angular2-quickstart@1.0.0 build: `ng build --prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/dgreen/.nvm/versions/node/v7.8.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/dgreen/.nvm/versions/node/v7.8.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid aws-cognito-angular2-quickstart@1.0.0
16 verbose cwd /Users/dgreen/code/aws-cognito-angular2-quickstart
17 error Darwin 16.5.0
18 error argv "/Users/dgreen/.nvm/versions/node/v7.8.0/bin/node" "/Users/dgreen/.nvm/versions/node/v7.8.0/bin/npm" "run" "build"
19 error node v7.8.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error aws-cognito-angular2-quickstart@1.0.0 build: `ng build --prod`
23 error Exit status 1
24 error Failed at the aws-cognito-angular2-quickstart@1.0.0 build script 'ng build --prod'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the aws-cognito-angular2-quickstart package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     ng build --prod
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs aws-cognito-angular2-quickstart
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls aws-cognito-angular2-quickstart
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

ng --version
@angular/cli: 1.0.0
node: 7.8.0
os: darwin x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/platform-server: 4.0.0
@angular/router: 4.0.0
@angular/animations: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

any clues what might be amiss in my environment that is causing this?

**Comment by vbudilov** [comment]
Fixed. Do a git pull and try running ng build --prod again

**Comment by greendavegreen** [comment]
agreed.  all clean now.  thx!
