### ISSUE TITLE
support Authentication Flow for Users Created by Administrators or Developers

### ISSUE THREAD

**Issue by greendavegreen** [awslabs/aws-cognito-angular2-quickstart#67]
[This AWS doc page](http://docs.aws.amazon.com/cognito/latest/developerguide/how-to-create-user-accounts.html) details the flow for logging in users created by Administrators (which returns NEW_PASSWORD_REQUIRED on first login), and the user must initiate a password change before being allowed to log in.

currently, the quickstart supports self-signup well to get groups up and running, but does not have support for the callback/ui of the alternate login flow.

It would be great to support this alternate login flow.  The quickstart would be much more valuable to groups wishing to set up administrtor managed pools of users.

**Comment by vbudilov** [comment]
Hi @greendavegreen , 

Adding this isn't on the roadmap as of yet, but feel free to do a PR if you'd like.

**Comment by greendavegreen** [comment]
It might take a while, but if I get to a working password change component that can be used to support manually created accounts, I will be happy to bundle it up as a PR for the project.

**Comment by vbudilov** [comment]
https://github.com/awslabs/aws-cognito-angular2-quickstart/pull/71
