### ISSUE TITLE
Ionic2

### ISSUE THREAD

**Issue by chris-munn** [awslabs/aws-cognito-angular2-quickstart#8]
Sorry I know this came up in issue #5 but are there any intentions on making this work for ionic2 or even giving a quick guide? 

I know a lot of people who are looking for something just like this but with ionic2.

Many Thanks,

Chris

**Comment by vbudilov** [comment]
Hi @Munnster83, 

Thanks for reaching out! I have created an Ionic 2 version of this and will work on open-sourcing it. I will update this ticket with further information. 

Thanks,
Vladimir Budilov

**Comment by chris-munn** [comment]
Hello @vbudilov,

That is Fantastic news!
Cannot wait to see the Ionic2 version.

Will keep checking back regularly :)

Regards,

Chris

**Comment by vbudilov** [comment]
Hi @Munnster83 , 

Here's the ionic2 version. Enjoy! :)
https://github.com/vbudilov/aws-cognito-ionic2

Thanks,
Vladimir Budilov

**Comment by chris-munn** [comment]
Hey @vbudilov,

You sir are my new found hero, thank you very much I will most definitely start having a play with the repo today :)
