### ISSUE TITLE
AWS.Signers for Angular 2

### ISSUE THREAD

**Issue by kenny-lee-1992** [awslabs/aws-cognito-angular2-quickstart#85]
Dear,

I need AWS.Signers.V4 for my angular application, which use MQTT to connect IoT Shadow.

So how to use/import this ?

Thanks and Best Regards,

**Comment by vbudilov** [comment]
Hi @minhlong , I'm not sure what you mean. How is MQTT relevant to the cognito quickstart?

**Comment by kenny-lee-1992** [comment]
Hi @vbudilov ,

Thanks for your reply. After authenticated, i need to get the credential information for generate the URL ("Signature Version 4 Signing Process") to use for IoT. And i figure out that AWS support signer V4 in "node_modules\aws-sdk\lib\signers\v4.js", but i do not know how to apply to my angular 2 ?

Thanks and Best Regards

**Comment by vbudilov** [comment]
Hi @minhlong , take a look at this doc for more info: http://docs.aws.amazon.com/general/latest/gr/signature-v4-examples.html
